name: Docker Build User Profile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONTAINER_REGISTRY: docker.pkg.github.com # Container Registry name
  
jobs:

  publish:
    name: Docker Build User Profile

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chixcancode-projects/openhack-devops-team/userprofile
        username: ${{ github.actor }}
        password: ${{ secrets.githubtoken }}
        registry: docker.pkg.github.com
        tags: "latest, ${{ github.run_number }}" 
        workdir: ./apis/userprofile

  deploy:
    needs: [publish]
    name: User Profile App Service Deploy
    
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Login via Docker to GH'
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.githubtoken }}
    
      - name: 'Push to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'openhack4t18p479userprofile'
          images: ${{ env.CONTAINER_REGISTRY }}/chixcancode-projects/openhack-devops-team/userprofile:latest
          slot-name: 'staging'
          
  test:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
    - name: Test the Staging Slot
      run: echo ${env:PATH}
      shell: pwsh

    
  swap:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
             az webapp deployment slot swap  -g openhack4t18p479rg -n openhack4t18p479 --slot staging --target-slot production
