name: Docker Build User Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: openhack4t18p479userjava   # set this to your application's name
  CONTAINER_REGISTRY: docker.pkg.github.com # Container Registry name
  AZURE_RESOURCE_GROUP: openhack4t18p479rg  # set this to your Azure Resource group's name
  AZURE_APP_PLAN: openhack4t18p479plan  # set this to your App service plan's name - Needed only if you are provisioning the app in the workflow
  
jobs:

  publishPackage:
    name: Docker Build User Java

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: chixcancode-projects/openhack-devops-team/user-java
        username: ${{ github.actor }}
        password: ${{ secrets.githubtoken }}
        registry: docker.pkg.github.com
        workdir: ./apis/user-java

  deployPackage:
    needs: [publishPackage]
    
    name: Deploy from GitHub Packages to Azure App Services
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    
    - name: 'Deploy to Azure Web App for Container'   
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} 
        images: ${{ env.CONTAINER_REGISTRY }}/chixcancode-projects/openhack-devops-team/user-java:latest
    
    
